camera1:
  serial_no: "6CD1460300DF" # Note: Replace with actual serial number
  ip_address: "" # Note: Replace with actual IP address
  usb_port_id: ""
  device_type: ""
  rosbag_filename: ""
  initial_reset: false

  json_file_path: ""
  rosbag_filename: ""
  required: false

  depth_width: 848
  depth_height: 480
  enable_depth: true

  infra_width: 848
  infra_height: 480
  enable_infra1: false
  enable_infra2: false

  color_width: 848
  color_height: 480
  enable_color: true

  depth_fps: 15
  infra_fps: 15
  color_fps: 15

  enable_pointcloud: true
  pointcloud_texture_stream: "RS2_STREAM_COLOR" #use RS2_STREAM_ANY to avoid using texture
  pointcloud_texture_index: 0

  enable_sync: true
  align_depth: true

  base_frame_id: "1_d435e_camera_link"
  depth_frame_id: "camera1_depth_frame"
  infra1_frame_id: "camera1_infra1_frame"
  infra2_frame_id: "camera1_infra2_frame"
  color_frame_id: "camera1_color_frame"

  depth_optical_frame_id: "camera1_depth_optical_frame"
  infra1_optical_frame_id: "camera1_infra1_optical_frame"
  infra2_optical_frame_id: "camera1_infra2_optical_frame"
  color_optical_frame_id: "camera1_color_optical_frame"

  aligned_depth_to_color_frame_id: "camera1_aligned_depth_to_color_frame"
  aligned_depth_to_infra1_frame_id: "camera1_aligned_depth_to_infra1_frame"
  aligned_depth_to_infra2_frame_id: "camera1_aligned_depth_to_infra2_frame"

  publish_tf: true
  tf_publish_rate: 0

  odom_frame_id: "camera1_odom_frame"
  topic_odom_in: "camera1/odom_in"
  calib_odom_file: ""
  publish_odom_tf: false
  filters: ""
  clip_distance: -1
  allow_no_texture_points: false

##############################################################################
